### ISSUE TITLE
Add new ores from latest snapshot

### ISSUE THREAD

**Issue by StormDragon77** [StormDragon77/FixedInconsistencies#146]
May tweak palettes of ores.
Diamond and lapis may get a new texture or will just be slightly tweaked.

**Comment by StormDragon77** [comment]
temporarily using ores from 21w07a, will switch to new ones when released: https://twitter.com/JasperBoerstra/status/1362396465470005251

**Comment by Brun333rp** [comment]
you should change the title to reffer to 21w08 textures

**Comment by StormDragon77** [comment]
Lapis and emerald ores will now be left alone.

**Comment by StormDragon77** [comment]
Diamond has a new texture that falls more in line with the new ores while keeping the formation similar to the classic one. Lapis was tweaked to have bigger chunks. Waiting on new iron ore since another iteration has been made: https://twitter.com/JasperBoerstra/status/1366733338023665665
